# -*- coding: utf-8 -*-
"""DAV Exp 2 [Single Linear Regression (SimpleLinearRegression.csv)].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfIRlTcTxKShwqYOxzWToYzFFkO1Ow5J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

file = r'SimpleLinearRegression.csv'
data = pd.read_csv(file)

data.head()

data.head(15)

data.shape

data.info()

data.describe()

data.isnull()

x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

x

y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

lr = LinearRegression()

lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)
y_pred

y_test

lr.intercept_

lr.coef_

score = r2_score(y_test, y_pred)
score

lr.predict([[20]])

plt.scatter(x_train, y_train, color = 'red')
plt.title('Salary vs Experience (Training Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

plt.scatter(x_test, y_test, color = 'red')
plt.plot(x_test, y_pred, color = 'green')
plt.title('Salary vs Experience (Test Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()